const projectError = {
    "HELLOWORLD-ERROR-NONAME": {
        "code": "HELLOWORLD-ERROR-NONAME",
        "textTH": "คุณไม่ได้แจ้งชื่อไว้",
        "textEN": "Name is required",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
    "GET-PROJECT-BRIEF-DATA-NO-PROJECT-ID-PROVIDED": {
        "code": "GET-PROJECT-BRIEF-DATA-NO-PROJECT-ID-PROVIDED",
        "textTH": "ไม่มีข้อมูลกิจกรรมเนื่องจากไม่ได้ให้รหัสกิจกรรม",
        "textEN": "No project ID was provided",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
    "GET-PROJECT-BRIEF-DATA-NOT-EXIST": {
        "code": "GET-PROJECT-BRIEF-DATA-NOT-EXIST",
        "textTH": "ไม่มีข้อมูลกิจกรรมนี้",
        "textEN": "No information for this project",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
    "PROJECT-BRIEF-DATA-UPDATE-PROTECTED-DATA": {
        "code": "PROJECT-BRIEF-DATA-UPDATE-PROTECTED-DATA",
        "textTH": "ไม่สามารถแก้ไขข้อมูลบางอย่างได้ กรุณายกเลิกการแก้ไข",
        "textEN": "Some data provided cannot be edited",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
    "GET-PROJECT-FULL-DATA-NOT-EXIST": {
        "code": "GET-PROJECT-FULL-DATA-NOT-EXIST",
        "textTH": "ไม่มีข้อมูลกิจกรรมนี้",
        "textEN": "No full information for this project",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
    "GET-PROJECT-FULL-DATA-NO-PROJECT-ID-PROVIDED": {
        "code": "GET-PROJECT-FULL-DATA-NO-PROJECT-ID-PROVIDED",
        "textTH": "ไม่มีข้อมูลกิจกรรมเนื่องจากไม่ได้ให้รหัสกิจกรรม",
        "textEN": "No project ID was provided",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
    "PROJECT-FULL-DATA-UPDATE-PROTECTED-DATA": {
        "code": "PROJECT-FULL-DATA-UPDATE-PROTECTED-DATA",
        "textTH": "ไม่สามารถแก้ไขข้อมูลบางอย่างได้ กรุณายกเลิกการแก้ไข",
        "textEN": "Some data provided cannot be edited",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
    "GET-PROJECT-ANNOUNCEMENT-NO-PROJECT-ID-PROVIDED": {
        "code": "GET-PROJECT-ANNOUNCEMENT-NO-PROJECT-ID-PROVIDED",
        "textTH": "ไม่มีข้อมูลประกาศเนื่องจากไม่ได้ให้รหัสกิจกรรม",
        "textEN": "No project ID was provided",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
    "PROJECT-ANNOUNCEMENT-UPDATE-PROTECTED-DATA": {
        "code": "PROJECT-ANNOUNCEMENT-UPDATE-PROTECTED-DATA",
        "textTH": "ไม่สามารถแก้ไขข้อมูลบางอย่างได้ กรุณายกเลิกการแก้ไข",
        "textEN": "Some data provided cannot be edited",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
    "PROJECT-ANNOUNCEMENT-CREATED-PROTECTED-DATA": {
        "code": "PROJECT-ANNOUNCEMENT-CREATED-PROTECTED-DATA",
        "textTH": "ไม่สามารถแก้ไขข้อมูลบางอย่างได้ กรุณายกเลิกการแก้ไข",
        "textEN": "Some data provided cannot be edited",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
    "PROJECT-JOIN-PCP-FAILED-SEAT-FULL": {
        "code": "PROJECT-JOIN-PCP-FAILED-SEAT-FULL",
        "textTH": "ไม่สามารถเข้าร่วมกิจกรรมได้ เนื่องจากรับเต็มจำนวนแล้ว",
        "textEN": "No seats available for joining this project",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "GET-PROJECT-PCP-LIST-NO-PROJECT-ID-PROVIDED": {
        "code": "GET-PROJECT-PCP-LIST-NO-PROJECT-ID-PROVIDED",
        "textTH": "ไม่มีข้อมูลผู้เข้าร่วมกิจกรรมเนื่องจากไม่ได้ให้รหัสกิจกรรม",
        "textEN": "No project ID was provided",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
    "JOIN-PROJECT-AS-PCP-FAILED-NOT-MEET-CRITERIA": {
        "code": "JOIN-PROJECT-AS-PCP-FAILED-NOT-MEET-CRITERIA",
        "textTH": "ไม่สามารถเข้าร่วมกิจกรรมได้ เนื่องจากไม่ผ่านเงื่อนไขการสมัคร",
        "textEN": "Failed to join a project because all criteria were not met",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
}

module.exports = projectError