const activitySuccess = {
    "ACTIVITY-GET-CHECK-IN-CODE-SUCCESS": {
        "code": "ACTIVITY-GET-CHECK-IN-CODE-SUCCESS",
        "textTH": "รับข้อมูลรหัสเข้าร่วมกิจกรรมสำเร็จ",
        "textEN": "Get activity check in code success",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "CHECK-IN-BULK-SUCCESS": {
        "code": "CHECK-IN-BULK-SUCCESS",
        "textTH": "ลงทะเบียนคนเข้าร่วมกิจกรรมสำเร็จ",
        "textEN": "Bulk check-in success",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "EVALUATION-FORM-RETRIEVE-STATUS-SUCCESS": {
        "code": "EVALUATION-FORM-RETRIEVE-STATUS-SUCCESS",
        "textTH": "รับข้อมูลสถานะของแบบประเมินกิจกรรมสำเร็จ",
        "textEN": "Retrieve status of an evaluation form success",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "EVALUATION-FORM-EDIT-STATUS-SUCCESS": {
        "code": "EVALUATION-FORM-EDIT-STATUS-SUCCESS",
        "textTH": "แก้ไขข้อมูลสถานะของแบบประเมินกิจกรรมสำเร็จ",
        "textEN": "Edit status of an evaluation form success",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "EVALUATION-FORM-USER-DONE-RETRIEVE-STATUS-SUCCESS": {
        "code": "EVALUATION-FORM-USER-DONE-RETRIEVE-STATUS-SUCCESS",
        "textTH": "รับข้อมูลการทำแบบประเมินกิจกรรมของผู้ใช้สำเร็จ",
        "textEN": "Retrieve status if user has done an evaluation form success",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "EVALUATION-FORM-COUNT-SUCCESS": {
        "code": "EVALUATION-FORM-COUNT-SUCCESS",
        "textTH": "นับจำนวนข้อมูลของแบบประเมินกิจกรรมสำเร็จ",
        "textEN": "Count an evaluation form success",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "EVALUATION-FORM-SUBMISSION-SUCCESS": {
        "code": "EVALUATION-FORM-SUBMISSION-SUCCESS",
        "textTH": "ประเมินกิจกรรมสำเร็จ",
        "textEN": "Evaluated success ",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "CERTIFICATE-GET-USER-STATUS-SUCCESS": {
        "code": "CERTIFICATE-GET-USER-STATUS-SUCCESS",
        "textTH": "ดึงข้อมูลสถานะของเกียรติบัตรสำหรับผู้ใช้คนนี้สำเร็จ",
        "textEN": "Get certification status of this user success",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "CERTIFICATE-EDIT-CERT-STATUS-SUCCESS": {
        "code": "CERTIFICATE-EDIT-CERT-STATUS-SUCCESS",
        "textTH": "แก้ไขสถานะการออกเกียรติบัตรสำเร็จ",
        "textEN": "Edit certification status success",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "CERTIFICATE-GET-DEFAULT-DATA-SUCCESS": {
        "code": "CERTIFICATE-GET-DEFAULT-DATA-SUCCESS",
        "textTH": "ดึงข้อมูลพื้นฐานของเกียรติบัตรสำเร็จ",
        "textEN": "Get certificate default data success",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "CERTIFICATE-EDIT-DEFAULT-DATA-SUCCESS": {
        "code": "CERTIFICATE-EDIT-DEFAULT-DATA-SUCCESS",
        "textTH": "แก้ไขข้อมูลพื้นฐานของเกียรติบัตรสำเร็จ",
        "textEN": "Edit certificate default data success",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "CERTIFICATE-GENERATE-SUCCESS": {
        "code": "CERTIFICATE-GENERATE-SUCCESS",
        "textTH": "สร้างเกียรติบัตรสำเร็จ",
        "textEN": "Generate a certification success",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "CERTIFICATE-INFO-GET-DATA-SUCCESS": {
        "code": "CERTIFICATE-INFO-GET-DATA-SUCCESS",
        "textTH": "รับข้อมูลของเกียรติบัตรสำเร็จ",
        "textEN": "Get a certification info success",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
}

module.exports = activitySuccess