const projectSuccess = {
    "HELLOWORLD-SUCCESS": {
        "code": "HELLOWORLD-SUCCESS",
        "textTH": "สวัสดีจากระบบ",
        "textEN": "Hello from CMSO!",
        "shouldContactAdmin": false,
        "shouldTryAgain": true,
    },
    "GET-GLOBAL-ANNOUNCEMENT-SUCCESS": {
        "code": "GET-GLOBAL-ANNOUNCEMENT-SUCCESS",
        "textTH": "ดึงข้อมูลประกาศกลางสำเร็จ",
        "textEN": "Get global announcement success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "SEARCH-PROJECT-BY-NAME-PAGE-SUCCESS": {
        "code": "SEARCH-PROJECT-BY-NAME-PAGE-SUCCESS",
        "textTH": "ค้นหาข้อมูลกิจกรรมสำเร็จ",
        "textEN": "Search for projects success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "GET-PROJECT-BRIEF-DATA-SUCCESS": {
        "code": "GET-PROJECT-BRIEF-DATA-SUCCESS",
        "textTH": "รับข้อมูลกิจกรรมสำเร็จ",
        "textEN": "Retreive project brief data success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "UPDATE-PROJECT-BRIEF-DATA-SUCCESS": {
        "code": "UPDATE-PROJECT-BRIEF-DATA-SUCCESS",
        "textTH": "แก้ไขข้อมูลกิจกรรมสำเร็จ",
        "textEN": "Update project brief data success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "DELETE-PROJECT-SUCCESS": {
        "code": "DELETE-PROJECT-SUCCESS",
        "textTH": "ลบกิจกรรมสำเร็จ",
        "textEN": "Delete project success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "GET-PROJECT-FULL-DATA-SUCCESS": {
        "code": "GET-PROJECT-FULL-DATA-SUCCESS",
        "textTH": "รับข้อมูลกิจกรรมสำเร็จ",
        "textEN": "Retreive project full data success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "UPDATE-PROJECT-FULL-DATA-SUCCESS": {
        "code": "UPDATE-PROJECT-FULL-DATA-SUCCESS",
        "textTH": "แก้ไขข้อมูลกิจกรรมสำเร็จ",
        "textEN": "Update project full data success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "GET-PROJECT-ANNOUNCEMENT-SUCCESS": {
        "code": "GET-PROJECT-ANNOUNCEMENT-SUCCESS",
        "textTH": "รับข้อมูลประกาศของกิจกรรมสำเร็จ",
        "textEN": "Retreive project announcement success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "UPDATE-PROJECT-ANNOUNCEMENT-SUCCESS": {
        "code": "UPDATE-PROJECT-ANNOUNCEMENT-SUCCESS",
        "textTH": "แก้ไขข้อมูลประกาศของกิจกรรมสำเร็จ",
        "textEN": "Updated project announcement success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "DELETE-PROJECT-ANNOUNCEMENT-SUCCESS": {
        "code": "DELETE-PROJECT-ANNOUNCEMENT-SUCCESS",
        "textTH": "ลบประกาศของกิจกรรมสำเร็จ",
        "textEN": "Deleted project announcement success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "CREATE-NEW-PROJECT-ANNOUNCEMENT-SUCCESS": {
        "code": "CREATE-NEW-PROJECT-ANNOUNCEMENT-SUCCESS",
        "textTH": "เพิ่มข้อมูลประกาศของกิจกรรมสำเร็จ",
        "textEN": "Added new project announcement success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "JOIN-PROJECT-PCP-SUCCESS": {
        "code": "JOIN-PROJECT-PCP-SUCCESS",
        "textTH": "เข้าร่วมกิจกรรมในฐานะผู้เข้าร่วม สำเร็จ",
        "textEN": "Join a project as participant successfully!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "JOIN-PROJECT-STF-SUCCESS": {
        "code": "JOIN-PROJECT-STF-SUCCESS",
        "textTH": "เข้าร่วมกิจกรรมในฐานะผู้จัดกิจกรรม สำเร็จ",
        "textEN": "Join a project as staff successfully!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "GET-PROJECT-CONSIDER-DATA-SUCCESS": {
        "code": "GET-PROJECT-CONSIDER-DATA-SUCCESS",
        "textTH": "รับข้อมูลพิจารณาโครงการสำเร็จ",
        "textEN": "Get project consideration data success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "EDIT-PROJECT-CONSIDER-DATA-SUCCESS": {
        "code": "EDIT-PROJECT-CONSIDER-DATA-SUCCESS",
        "textTH": "แก้ไขข้อมูลพิจารณาโครงการสำเร็จ",
        "textEN": "Edit project consideration data success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
}

module.exports = projectSuccess