const recruitmentSuccess = {
    "GET-PARTICIPANT-RECRUITMENT-LIST-SUCCESS": {
        "code": "GET-PARTICIPANT-RECRUITMENT-LIST-SUCCESS",
        "textTH": "ดึงรายชื่อประกาศรับสมัครผู้เข้าร่วมกิจกรรมสำเร็จ",
        "textEN": "Get participant recruitment list success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "GET-STAFF-RECRUITMENT-LIST-SUCCESS": {
        "code": "GET-STAFF-RECRUITMENT-LIST-SUCCESS",
        "textTH": "ดึงรายชื่อประกาศรับสมัครสตาฟสำเร็จ",
        "textEN": "Get staff recruitment list success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "CREATE-NEW-RECRUIT-PCP-SUCCESS": {
        "code": "CREATE-NEW-RECRUIT-PCP-SUCCESS",
        "textTH": "สร้างประกาศรับสมัครผู้เข้าร่วมกิจกรรมใหม่สำเร็จ",
        "textEN": "Create new participant recruitment success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "CREATE-NEW-RECRUIT-STF-SUCCESS": {
        "code": "CREATE-NEW-RECRUIT-STF-SUCCESS",
        "textTH": "สร้างประกาศรับสมัครผู้จัดกิจกรรมใหม่สำเร็จ",
        "textEN": "Create new staff recruitment success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "GET-RECRUITMENT-DATA-SUCCESS": {
        "code": "GET-RECRUITMENT-DATA-SUCCESS",
        "textTH": "ดึงข้อมูลประกาศรับสมัครสำเร็จ",
        "textEN": "Get recruitment information success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "UPDATE-RECRUITMENT-DATA-SUCCESS": {
        "code": "UPDATE-RECRUITMENT-DATA-SUCCESS",
        "textTH": "แก้ไขข้อมูลประกาศรับสมัครสำเร็จ",
        "textEN": "Update recruitment information success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "GET-RECRUITMENT-PCP-LIST-SUCCESS": {
        "code": "GET-RECRUITMENT-PCP-LIST-SUCCESS",
        "textTH": "ดึงข้อมูลผู้เข้าร่วมกิจกรรมจากประกาศรับสมัครสำเร็จ",
        "textEN": "Get recruitment information success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "GET-RECRUITMENT-STF-POS-LIST-SUCCESS": {
        "code": "GET-RECRUITMENT-STF-POS-LIST-SUCCESS",
        "textTH": "ดึงข้อมูลผู้จัดกิจกรรมจากเลขที่ตำแหน่งสำเร็จ",
        "textEN": "Get recruitment information success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "DELETE-RECRUITMENT-DATA-SUCCESS": {
        "code": "DELETE-RECRUITMENT-DATA-SUCCESS",
        "textTH": "ลบข้อมูลประกาศรับสมัครสำเร็จ",
        "textEN": "Delete recruitment information success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "CREATE-NEW-STF-POSITION-SUCCESS": {
        "code": "CREATE-NEW-STF-POSITION-SUCCESS",
        "textTH": "สร้างตำแหน่งรับใหม่สำหรับกิจกรรมสำเร็จ",
        "textEN": "Create new staff position success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "UPDATE-STF-POSITION-SUCCESS": {
        "code": "UPDATE-STF-POSITION-SUCCESS",
        "textTH": "แก้ไขตำแหน่งของกิจกรรมสำเร็จ",
        "textEN": "Edit staff position success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
    "DELETE-STF-POSITION-SUCCESS": {
        "code": "DELETE-STF-POSITION-SUCCESS",
        "textTH": "ลบข้อมูลตำแหน่งของกิจกรรมสำเร็จ",
        "textEN": "Delete staff position success!",
        "shouldContactAdmin": false,
        "shouldTryAgain": false,
    },
}

module.exports = recruitmentSuccess